integrations:
  last-fm:
    frequency: "daily"
    all: true
  wakatime:
    frequency: "daily"
    all: true
  twitter:
    frequency: "daily"
    all: true
  # clockify:
  # spotify:
  # goodreads:
  # rescuetime:
  # oura-ring:
  # google-fit:
  # pocket-casts:
